#!/bin/bash

# This script takes in input the folder with the reads of the samples that you want to co-assemble and produce
# and assemble them

input_folder=$var1			#Directory containing tmp_reads (generated by SampleLinker.sh)
ncores=$var2                #Number of cores
mem=$var3                   #Memory used per assembly
e=$var4                     #Fastq extension

coassembly_name=$(basename $input_folder)

#PATHS to tools
TOOLSFOLDER=/shares/CIBIO-Storage/CM/cmstore/tools
PYTHONFOLDER=/shares/CIBIO-Storage/CM/cmstore/tools/anaconda3/bin/

#TMP_FOLDER
TMP_FOLDER=SERVER_TEMPFOLDER=/shares/CIBIO-Storage/CM/scratch/users/davide.golzato/tmp_scratch/

#COASSEMBLY FOLDER
coassembly_reads_folder=${input_folder}/tmp_reads/
coassembly_output_folder=${input_folder}/megahit/
echo $coassembly_output_folder

#Minimum requirements: 1) n R1 = n R2; 2) order of R1 = order of R2
R1=(`ls ${coassembly_reads_folder}/*_R1.${e}`)
R2=(`ls ${coassembly_reads_folder}/*_R2.${e}`)
UN=(`ls -A ${coassembly_reads_folder}/*_UN.${e}`)

if [[ "${R1[@]%.*}" == "${R2[@]%.*}" ]]; then echo -e "R1 and R2 not paired" ; exit 1 ; fi

R1=$(echo ${R1[@]} | tr " " ",");
R2=$(echo ${R2[@]} | tr " " ",");
UN=$(echo ${UN[@]} | tr " " ",");
logs="${input_folder}/logs"

pmega="/shares/CIBIO-Storage/CM/cmstore/tools/megahit-1.1.1/megahit"

mkdir -p ${logs} 

if [ ! -z ${R1} ]; then 
    if [ ! -z ${UN} ]; then 
        ${pmega} --verbose -1 ${R1} -2 ${R2} -r ${UN} -o "${coassembly_output_folder}" -t ${ncores} -m ${mem}e9 2> ${logs}/megahit.${coassembly_name}.e 1> ${logs}/megahit.${coassembly_name}.o; 
    else 
        ${pmega} --verbose -1 ${R1} -2 ${R2} -o "${coassembly_output_folder}" -t ${ncores} -m ${mem}e9 2> ${logs}/megahit.${coassembly_name}.e 1> ${logs}/megahit.${coassembly_name}.o; 
    fi
else ${pmega} -r ${UN} -o ${coassembly_output_folder} -t ${ncores} -m ${mem}e9 2> ${logs}/megahit.${coassembly_name}.e 1> ${logs}/megahit.${coassembly_name}.o;
fi

rm -rf ${coassembly_output_folder}/intermediate_contigs
rm ${coassembly_output_folder}/done
rm ${coassembly_output_folder}/log
rm ${coassembly_output_folder}/opts.txt
